// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhymvqbjthkjmfwrlmtn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oeW12cWJqdGhram1md3JsbXRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDMwNTEsImV4cCI6MjA2MDYxOTA1MX0.SII-m2zMD5MiwpuJlXBJJaOrPXGHGB-TDchWSE-hTQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);